"""add cascade delete to analytics events

Revision ID: 8d124189b3d5
Revises: a7fb37550b5f
Create Date: 2026-06-09 16:06:13.814021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d124189b3d5'
down_revision: Union[str, Sequence[str], None] = 'a7fb37550b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analytics_events_url_id_fkey'), 'analytics_events', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_events', 'urls', ['url_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics_events', type_='foreignkey')
    op.create_foreign_key(op.f('analytics_events_url_id_fkey'), 'analytics_events', 'urls', ['url_id'], ['id'])
    # ### end Alembic commands ###
